//go:build integration

package postgres

import (
	"context"
	"reflect"
	"strings"
	"testing"

	"sqlmux/internal/db"
)

func TestSchemas(t *testing.T) {
	schemas, current, err := Schemas(context.Background(), connect(t, true))
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(schemas, []string{"agentable", "public"}) || current != "public" {
		t.Fatalf("schemas %v, current %q", schemas, current)
	}
}

// Partitions are left out, their parent listed; views and materialized
// views are in (§8.4).
func TestTables(t *testing.T) {
	ts, err := Tables(context.Background(), connect(t, true))
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	rows, kinds := map[string]float64{}, map[string]string{}
	for _, tb := range ts {
		names = append(names, tb.Schema+"."+tb.Name)
		rows[tb.Name], kinds[tb.Name] = tb.Rows, tb.Kind
	}
	want := []string{
		"agentable.agent", "agentable.agent_version", "agentable.goal",
		"public.mv_order_by_status", "public.t_event", "public.t_log", "public.t_order",
		"public.t_order_item", "public.t_sku", "public.t_user", "public.v_paid_order",
	}
	if !reflect.DeepEqual(names, want) {
		t.Fatalf("tables %v", names)
	}
	if rows["t_order"] != 6000 || rows["v_paid_order"] >= 0 {
		t.Errorf("estimates: t_order %v, a view %v", rows["t_order"], rows["v_paid_order"])
	}
	if kinds["t_order"] != "r" || kinds["t_event"] != "p" || kinds["v_paid_order"] != "v" || kinds["mv_order_by_status"] != "m" {
		t.Errorf("kinds %v", kinds) // what sorts them into Tables and Views (§7.8)
	}
}

func TestTableColumns(t *testing.T) {
	c := connect(t, true)
	cols := func(table string) db.Columns {
		t.Helper()
		cs, err := TableColumns(context.Background(), c, "public", table)
		if err != nil {
			t.Fatal(err)
		}
		return cs
	}
	order := cols("t_order")
	byName := map[string]db.Column{}
	for _, col := range order.Cols {
		byName[col.Name] = col
	}
	for name, want := range map[string]db.Column{
		"id":         {Name: "id", Type: "bigint", NotNull: true, Default: "nextval('t_order_id_seq'::regclass)"},
		"status":     {Name: "status", Type: "order_status", NotNull: true, Default: "'pending'::order_status", Enum: []string{"pending", "queued", "running", "done", "failed"}},
		"amount":     {Name: "amount", Type: "numeric(10,2)", NotNull: true},
		"paid":       {Name: "paid", Type: "boolean"},
		"meta":       {Name: "meta", Type: "jsonb"},
		"created_at": {Name: "created_at", Type: "timestamp with time zone", NotNull: true, Default: "now()"},
		"deleted_at": {Name: "deleted_at", Type: "timestamp with time zone"},
	} {
		if got := byName[name]; !reflect.DeepEqual(got, want) {
			t.Errorf("%s: %+v, want %+v", name, got, want)
		}
	}
	if len(order.Cols) != 10 || order.Cols[0].Name != "id" || order.Cols[9].Name != "deleted_at" {
		t.Errorf("columns out of attnum order: %v", order.Cols)
	}
	if !reflect.DeepEqual(order.PK, []string{"id"}) || order.Unique != nil {
		t.Errorf("t_order keys: pk %v unique %v", order.PK, order.Unique)
	}

	// keys in key order, not column order
	if ev := cols("t_event"); !reflect.DeepEqual(ev.PK, []string{"occurred_at", "id"}) {
		t.Errorf("composite pk %v", ev.PK)
	}
	// code, title (INCLUDE barcode) and (title, code) can identify a row; the
	// nullable barcode, the partial and the expression index can't
	if sku := cols("t_sku"); sku.PK != nil || !reflect.DeepEqual(sku.Unique, [][]string{{"code"}, {"title"}, {"title", "code"}}) {
		t.Errorf("t_sku keys: pk %v unique %v", sku.PK, sku.Unique)
	}
	if log := cols("t_log"); log.PK != nil || log.Unique != nil || len(log.Cols) != 2 {
		t.Errorf("t_log: %+v", log)
	}
}

// An identity column's default is how it is generated: it has no
// expression (F3.32).
func TestTableColumnsIdentity(t *testing.T) {
	ctx := context.Background()
	c, err := Connect(ctx, ownDB(t), "", false)
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	if _, err := c.Query(ctx, "create table ids (a int generated always as identity, b int generated by default as identity, n int)"); err != nil {
		t.Fatal(err)
	}
	cs, err := TableColumns(ctx, c, "public", "ids")
	if err != nil || cs.Cols[0].Default != "generated always as identity" || cs.Cols[1].Default != "generated by default as identity" || cs.Cols[2].Default != "" {
		t.Errorf("%+v %v", cs.Cols, err)
	}
}

// DDL as the palette previews it (F4.2): a table's columns and
// constraints, the indexes a constraint makes left out; a view's query, a
// materialized view's with its indexes.
func TestDDL(t *testing.T) {
	ctx := context.Background()
	c := connect(t, true)
	for name, want := range map[string]string{
		"t_event": "create table public.t_event (\n  id bigint not null,\n  occurred_at timestamp with time zone not null,\n  kind text not null,\n" +
			"  constraint t_event_pkey PRIMARY KEY (occurred_at, id)\n);",
		"v_paid_order":       "create view public.v_paid_order as\n SELECT id,\n    user_id,\n    amount\n   FROM t_order\n  WHERE paid;",
		"mv_order_by_status": "create materialized view public.mv_order_by_status as\n SELECT status,\n    count(*) AS n\n   FROM t_order\n  GROUP BY status;",
	} {
		if got, err := DDL(ctx, c, "public", name); err != nil || got != want {
			t.Errorf("%s: %v\n%s", name, err, got)
		}
	}
	for name, want := range map[string]string{
		"t_order": `create table public.t_order (
  id bigint not null default nextval('t_order_id_seq'::regclass),
  user_id bigint not null,
  status order_status not null default 'pending'::order_status,
  amount numeric(10,2) not null,
  paid boolean,
  meta jsonb,
  raw json,
  note text,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  constraint t_order_pkey PRIMARY KEY (id),
  constraint t_order_user_id_fkey FOREIGN KEY (user_id) REFERENCES t_user(id)
);`,
		"t_sku": `create table public.t_sku (
  code text not null,
  barcode text,
  title text not null,
  price numeric(10,2)
);
CREATE UNIQUE INDEX t_sku_barcode ON public.t_sku USING btree (barcode);
CREATE UNIQUE INDEX t_sku_code ON public.t_sku USING btree (code);
CREATE UNIQUE INDEX t_sku_lower_title ON public.t_sku USING btree (lower(title));
CREATE UNIQUE INDEX t_sku_title ON public.t_sku USING btree (title) INCLUDE (barcode);
CREATE UNIQUE INDEX t_sku_title_code ON public.t_sku USING btree (title, code);
CREATE UNIQUE INDEX t_sku_title_priced ON public.t_sku USING btree (title) WHERE (price IS NOT NULL);`,
	} {
		if got, err := DDL(ctx, c, "public", name); err != nil || got != want {
			t.Errorf("%s: %v\n%s", name, err, got)
		}
	}

	own, err := Connect(ctx, ownDB(t), "", false)
	if err != nil {
		t.Fatal(err)
	}
	defer own.Close()
	if _, err := own.Exec(ctx, `create table "Ids" (a int generated always as identity primary key, b int generated by default as identity unique,
		n int check (n > 0), g int generated always as (n * 2) stored); create index ids_n on "Ids" (n);
		create materialized view mv as select 1 as x; create index mv_x on mv (x);
		create table self (id int primary key, code text not null, parent text);
		create unique index self_code on self (code); alter table self add foreign key (parent) references self (code);
		create table other (code text references self (code)); create table bare ()`, 0); err != nil {
		t.Fatal(err)
	}
	want := "create table public.\"Ids\" (\n  a integer not null generated always as identity,\n  b integer not null generated by default as identity,\n" +
		"  n integer,\n  g integer,\n  constraint \"Ids_pkey\" PRIMARY KEY (a),\n  constraint \"Ids_b_key\" UNIQUE (b),\n" +
		"  constraint \"Ids_n_check\" CHECK ((n > 0))\n);\nCREATE INDEX ids_n ON public.\"Ids\" USING btree (n);"
	if got, err := DDL(ctx, own, "public", "Ids"); err != nil || got != want {
		t.Errorf("identity, generated, quoted: %v\n%s", err, got)
	}
	if got, err := DDL(ctx, own, "public", "mv"); err != nil || !strings.HasSuffix(got, ";\nCREATE INDEX mv_x ON public.mv USING btree (x);") {
		t.Errorf("a materialized view's index: %v\n%s", err, got)
	}
	// a unique index foreign keys reference, its table's own and another's, is no constraint's
	want = "create table public.self (\n  id integer not null,\n  code text not null,\n  parent text,\n  constraint self_pkey PRIMARY KEY (id),\n" +
		"  constraint self_parent_fkey FOREIGN KEY (parent) REFERENCES self(code)\n);\nCREATE UNIQUE INDEX self_code ON public.self USING btree (code);"
	if got, err := DDL(ctx, own, "public", "self"); err != nil || got != want {
		t.Errorf("referenced: %v\n%s", err, got)
	}
	if got, err := DDL(ctx, own, "public", "bare"); err != nil || got != "create table public.bare ();" {
		t.Errorf("no columns: %v %q", err, got)
	}
}
